spring.application.name=appchatbackend

spring.data.mongodb.uri=mongodb+srv://tranquochoan349_db_user:Hoa01218816812@test.e6jvj2d.mongodb.net/appchat?retryWrites=true&w=majority&appName=Test

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

jwt.secret=7a4f2c8d1e9b3f6a0d5c2e8b4f1a7d3c9e6b2f5a8d1c4e7b0f3a6d9c2e5b8f1
jwt.expiration=900000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000

# Upload config
upload.dir=uploads
upload.max-file-size=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8080

# Ngrok config
ngrok.public-url=https://tintometric-serafina-nonbinding.ngrok-free.dev

