spring.application.name=appchatbackend

spring.mongodb.uri=mongodb+srv://tranquochoan349_db_user:Hoa01218816812@test.e6jvj2d.mongodb.net/appchat?retryWrites=true&w=majority&appName=Test

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

